-- 005: Final scientist/investor classifications and service-provider rollout, 2026-09-11.
-- Select the existing business database before executing; run after 004.
-- No DDL or resource deletion. Existing new fields, including intentional blanks, are preserved.
-- Legacy manager achievements stay as historical records; new service categories start without fabricated content.
SET NAMES utf8mb4;
START TRANSACTION;

UPDATE content_resource c JOIN content_resource_view v ON v.resource_id=c.id AND v.audience='scientist' AND v.category='technology'
SET c.payload=JSON_SET(c.payload,
  '$.attributes.scientistTechnologyField', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistTechnologyField'),JSON_EXTRACT(c.payload,'$.attributes.scientistTechnologyField'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.technologyField')) WHEN '小分子' THEN '小分子' WHEN '抗体' THEN '抗体' WHEN '多肽' THEN '多肽' WHEN '类器官' THEN '类器官' WHEN '基因与细胞治疗' THEN '基因与细胞治疗' WHEN '其他领域' THEN '其他领域' ELSE '' END)) AS JSON),
  '$.attributes.scientistResearchStage', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistResearchStage'),JSON_EXTRACT(c.payload,'$.attributes.scientistResearchStage'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.researchStage')) WHEN '早期研究' THEN '早期研究' WHEN '临床前研究' THEN '临床前研究' WHEN '临床研究' THEN '临床研究' WHEN '申请上市' THEN '申请上市' WHEN '批准上市' THEN '批准上市' ELSE '' END)) AS JSON),
  '$.attributes.scientistCooperationMode', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistCooperationMode'),JSON_EXTRACT(c.payload,'$.attributes.scientistCooperationMode'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.cooperationMode')) WHEN '技术转让' THEN '技术转让' WHEN '技术授权' THEN '技术授权' WHEN '其他模式' THEN '其他模式' ELSE '' END)) AS JSON)), c.version=c.version+1, c.updated_at=CURRENT_TIMESTAMP(6)
WHERE c.resource_type='technology' AND (NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistTechnologyField') OR NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistResearchStage') OR NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistCooperationMode'));

UPDATE content_resource c JOIN content_resource_view v ON v.resource_id=c.id AND v.audience='scientist' AND v.category='patent'
SET c.payload=JSON_SET(c.payload,
  '$.attributes.scientistPatentField', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistPatentField'),JSON_EXTRACT(c.payload,'$.attributes.scientistPatentField'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.patentField')) WHEN '小分子' THEN '小分子' WHEN '抗体' THEN '抗体' WHEN '多肽' THEN '多肽' WHEN '类器官' THEN '类器官' WHEN '基因与细胞治疗' THEN '基因与细胞治疗' WHEN '其他领域' THEN '其他领域' ELSE '' END)) AS JSON),
  '$.attributes.scientistCooperationMode', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistCooperationMode'),JSON_EXTRACT(c.payload,'$.attributes.scientistCooperationMode'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.cooperationMode')) WHEN '专利转让' THEN '专利转让' WHEN '专利授权' THEN '专利授权' WHEN '其他模式' THEN '其他模式' WHEN '专利全权转让' THEN '专利转让' WHEN '独占许可' THEN '专利授权' WHEN '排他许可' THEN '专利授权' WHEN '专项授权使用' THEN '专利授权' ELSE '' END)) AS JSON)), c.version=c.version+1, c.updated_at=CURRENT_TIMESTAMP(6)
WHERE c.resource_type='patent' AND (NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistPatentField') OR NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistCooperationMode'));

UPDATE content_resource c JOIN content_resource_view v ON v.resource_id=c.id AND v.audience='scientist' AND v.category='data'
SET c.payload=JSON_SET(c.payload,
  '$.attributes.scientistDataType', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistDataType'),JSON_EXTRACT(c.payload,'$.attributes.scientistDataType'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.dataType')) WHEN '临床前全套数据' THEN '临床前全套数据' WHEN '临床研究数据' THEN '临床研究数据' WHEN '真实世界RWD数据' THEN '真实世界RWD数据' WHEN '其他数据' THEN '其他数据' ELSE '' END)) AS JSON),
  '$.attributes.scientistComplianceMaturity', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistComplianceMaturity'),JSON_EXTRACT(c.payload,'$.attributes.scientistComplianceMaturity'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.complianceMaturity')) WHEN '仅限研究使用' THEN '仅限研究使用' WHEN '已脱敏合规' THEN '已脱敏合规' WHEN '可商用授权' THEN '可商用授权' WHEN '其他' THEN '其他' ELSE '' END)) AS JSON),
  '$.attributes.scientistCooperationMode', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistCooperationMode'),JSON_EXTRACT(c.payload,'$.attributes.scientistCooperationMode'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.cooperationMode')) WHEN '数据永久授权' THEN '数据永久授权' WHEN '单次项目调取' THEN '单次项目调取' WHEN '其他模式' THEN '其他模式' ELSE '' END)) AS JSON)), c.version=c.version+1, c.updated_at=CURRENT_TIMESTAMP(6)
WHERE c.resource_type='data' AND (NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistDataType') OR NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistComplianceMaturity') OR NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistCooperationMode'));

UPDATE content_resource c JOIN content_resource_view v ON v.resource_id=c.id AND v.audience='scientist' AND v.category='talent'
SET c.payload=JSON_SET(c.payload,
  '$.attributes.scientistTalentType', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistTalentType'),JSON_EXTRACT(c.payload,'$.attributes.scientistTalentType'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.talentType')) WHEN '投融资产业专家' THEN '投融资产业专家' WHEN '商业化运营人才' THEN '商业化运营人才' WHEN '其他人才' THEN '其他人才' ELSE '' END)) AS JSON),
  '$.attributes.scientistCooperationMode', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistCooperationMode'),JSON_EXTRACT(c.payload,'$.attributes.scientistCooperationMode'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.cooperationMode')) WHEN '全职' THEN '全职' WHEN '项目制' THEN '项目制' WHEN '技术顾问' THEN '技术顾问' ELSE '' END)) AS JSON)), c.version=c.version+1, c.updated_at=CURRENT_TIMESTAMP(6)
WHERE c.resource_type='talent' AND (NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistTalentType') OR NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistCooperationMode'));

UPDATE content_resource c JOIN content_resource_view v ON v.resource_id=c.id AND v.audience='scientist' AND v.category='service'
SET c.payload=JSON_SET(c.payload,
  '$.attributes.scientistServiceType', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistServiceType'),JSON_EXTRACT(c.payload,'$.attributes.scientistServiceType'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.serviceType')) WHEN 'CXO服务' THEN 'CXO服务' WHEN '骊珠整体解决方案' THEN '骊珠整体解决方案' WHEN '增值服务' THEN '增值服务' WHEN 'CRO服务' THEN 'CXO服务' WHEN 'CDMO服务' THEN 'CXO服务' ELSE '' END)) AS JSON),
  '$.attributes.scientistQualification', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistQualification'),JSON_EXTRACT(c.payload,'$.attributes.scientistQualification'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.qualification')) WHEN '丰富落地案例' THEN '丰富落地案例' ELSE '' END)) AS JSON),
  '$.attributes.scientistCooperationMode', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistCooperationMode'),JSON_EXTRACT(c.payload,'$.attributes.scientistCooperationMode'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.cooperationMode')) WHEN '单项目合作' THEN '单项目合作' WHEN '年度框架合作' THEN '年度框架合作' WHEN '其他模式' THEN '其他模式' WHEN '单项项目外包' THEN '单项目合作' ELSE '' END)) AS JSON)), c.version=c.version+1, c.updated_at=CURRENT_TIMESTAMP(6)
WHERE c.resource_type='service' AND (NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistServiceType') OR NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistQualification') OR NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.scientistCooperationMode'));

UPDATE content_resource c JOIN content_resource_view v ON v.resource_id=c.id AND v.audience='investor' AND v.category='project'
SET c.payload=JSON_SET(c.payload,
  '$.attributes.investorProjectType', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorProjectType'),JSON_EXTRACT(c.payload,'$.attributes.investorProjectType'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.projectType')) WHEN '早期创新药项目' THEN '早期创新药项目' WHEN '仿制药项目' THEN '仿制药项目' WHEN '改良型新药项目' THEN '改良型新药项目' WHEN '中药创新项目' THEN '中药创新项目' WHEN '原料药/API 项目' THEN '原料药/API 项目' WHEN '其他项目' THEN '其他项目' ELSE '' END)) AS JSON),
  '$.attributes.investorResearchStage', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorResearchStage'),JSON_EXTRACT(c.payload,'$.attributes.investorResearchStage'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.researchStage')) WHEN '早期研究' THEN '早期研究' WHEN '临床前研究' THEN '临床前研究' WHEN '临床研究' THEN '临床研究' WHEN '申请上市' THEN '申请上市' WHEN '批准上市' THEN '批准上市' WHEN '1期临床' THEN '临床研究' WHEN '2期临床' THEN '临床研究' WHEN '3期临床' THEN '临床研究' ELSE '' END)) AS JSON),
  '$.attributes.investorIndications', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorIndications'),JSON_EXTRACT(c.payload,'$.attributes.investorIndications'),JSON_MERGE_PRESERVE(JSON_ARRAY(),IF(JSON_CONTAINS(JSON_EXTRACT(c.payload,'$.attributes.indications'),JSON_QUOTE('肿瘤疾病')),JSON_ARRAY('肿瘤疾病'),JSON_ARRAY()),IF(JSON_CONTAINS(JSON_EXTRACT(c.payload,'$.attributes.indications'),JSON_QUOTE('代谢与内分泌疾病')),JSON_ARRAY('代谢与内分泌疾病'),JSON_ARRAY()),IF(JSON_CONTAINS(JSON_EXTRACT(c.payload,'$.attributes.indications'),JSON_QUOTE('神经系统疾病')),JSON_ARRAY('神经系统疾病'),JSON_ARRAY()),IF(JSON_CONTAINS(JSON_EXTRACT(c.payload,'$.attributes.indications'),JSON_QUOTE('心血管系统')),JSON_ARRAY('心血管系统'),JSON_ARRAY()),IF(JSON_CONTAINS(JSON_EXTRACT(c.payload,'$.attributes.indications'),JSON_QUOTE('其他适应症')),JSON_ARRAY('其他适应症'),JSON_ARRAY()))) AS JSON)), c.version=c.version+1, c.updated_at=CURRENT_TIMESTAMP(6)
WHERE c.resource_type='project' AND (NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorProjectType') OR NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorResearchStage') OR NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorIndications'));

UPDATE content_resource c JOIN content_resource_view v ON v.resource_id=c.id AND v.audience='investor' AND v.category='mah'
SET c.payload=JSON_SET(c.payload,
  '$.attributes.investorMahType', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorMahType'),JSON_EXTRACT(c.payload,'$.attributes.investorMahType'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.mahType')) WHEN '化学药制剂 MAH 批件' THEN '化学药制剂 MAH 批件' WHEN '生物药制剂 MAH 批件' THEN '生物药制剂 MAH 批件' WHEN '中药 MAH 批件' THEN '中药 MAH 批件' WHEN '其他批件' THEN '其他批件' ELSE '' END)) AS JSON),
  '$.attributes.investorApprovalStatus', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorApprovalStatus'),JSON_EXTRACT(c.payload,'$.attributes.investorApprovalStatus'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.approvalStatus')) WHEN '已获批' THEN '已获批' WHEN '其他状态' THEN '其他状态' WHEN '已获批在效期内' THEN '已获批' ELSE '' END)) AS JSON),
  '$.attributes.investorTradeMode', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorTradeMode'),JSON_EXTRACT(c.payload,'$.attributes.investorTradeMode'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.tradeMode')) WHEN 'MAH 转让' THEN 'MAH 转让' WHEN '股权并购' THEN '股权并购' WHEN '委托生产' THEN '委托生产' WHEN '其他合作模式' THEN '其他合作模式' ELSE '' END)) AS JSON)), c.version=c.version+1, c.updated_at=CURRENT_TIMESTAMP(6)
WHERE c.resource_type='mah' AND (NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorMahType') OR NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorApprovalStatus') OR NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorTradeMode'));

UPDATE content_resource c JOIN content_resource_view v ON v.resource_id=c.id AND v.audience='investor' AND v.category='scene'
SET c.payload=JSON_SET(c.payload,
  '$.attributes.investorSceneType', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorSceneType'),JSON_EXTRACT(c.payload,'$.attributes.investorSceneType'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.sceneType')) WHEN '疗愈空间' THEN '疗愈空间' WHEN '社区康养场景' THEN '社区康养场景' WHEN '消费医疗场景' THEN '消费医疗场景' WHEN '中医药特色服务场景' THEN '中医药特色服务场景' WHEN '其他业态场景' THEN '其他业态场景' WHEN '社区康养医养场景' THEN '社区康养场景' ELSE '' END)) AS JSON),
  '$.attributes.investorMaturity', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorMaturity'),JSON_EXTRACT(c.payload,'$.attributes.investorMaturity'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.maturity')) WHEN '试点验证阶段' THEN '试点验证阶段' WHEN '小范围运营' THEN '小范围运营' WHEN '规模化可复制' THEN '规模化可复制' WHEN '其他阶段' THEN '其他阶段' ELSE '' END)) AS JSON),
  '$.attributes.investorInvestmentMode', CAST(IF(JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorInvestmentMode'),JSON_EXTRACT(c.payload,'$.attributes.investorInvestmentMode'),JSON_QUOTE(CASE JSON_UNQUOTE(JSON_EXTRACT(c.payload,'$.attributes.investmentMode')) WHEN '股权投资' THEN '股权投资' WHEN '品牌授权' THEN '品牌授权' WHEN '加盟扩张' THEN '加盟扩张' WHEN '其他模式' THEN '其他模式' WHEN '品牌授权输出' THEN '品牌授权' WHEN '其他合作模式' THEN '其他模式' ELSE '' END)) AS JSON)), c.version=c.version+1, c.updated_at=CURRENT_TIMESTAMP(6)
WHERE c.resource_type='scene' AND (NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorSceneType') OR NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorMaturity') OR NOT JSON_CONTAINS_PATH(c.payload,'one','$.attributes.investorInvestmentMode'));

COMMIT;
SELECT v.audience,v.category,COUNT(*) AS resource_count FROM content_resource_view v
WHERE v.audience IN ('scientist','investor','manager') GROUP BY v.audience,v.category ORDER BY v.audience,v.category;
