'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=process.argv[2]||path.resolve(__dirname,'../..');
const schema=JSON.parse(fs.readFileSync(path.join(root,'src/main/resources/catalog-schema.json'),'utf8'));
const expected=[
  [
    "technology",
    "技术",
    [
      [
        "kind",
        "交易意向",
        [
          "supply",
          "demand"
        ]
      ],
      [
        "technologyField",
        "技术领域",
        [
          "小分子",
          "抗体",
          "多肽",
          "类器官",
          "基因与细胞治疗",
          "其他领域"
        ]
      ],
      [
        "researchStage",
        "研发阶段",
        [
          "早期研究",
          "临床前研究",
          "临床研究",
          "申请上市",
          "批准上市"
        ]
      ],
      [
        "cooperationMode",
        "合作模式",
        [
          "技术转让",
          "技术授权",
          "其他模式"
        ]
      ]
    ]
  ],
  [
    "patent",
    "专利",
    [
      [
        "patentType",
        "专利类型",
        [
          "发明专利",
          "实用新型专利",
          "软著"
        ]
      ],
      [
        "patentField",
        "专利领域",
        [
          "小分子",
          "抗体",
          "多肽",
          "类器官",
          "基因与细胞治疗",
          "其他领域"
        ]
      ],
      [
        "patentStatus",
        "专利状态",
        [
          "有效授权",
          "实质审查中",
          "即将过期"
        ]
      ],
      [
        "cooperationMode",
        "合作模式",
        [
          "专利转让",
          "专利授权",
          "其他模式"
        ]
      ]
    ]
  ],
  [
    "mah",
    "MAH",
    [
      [
        "kind",
        "交易意向",
        [
          "supply",
          "demand"
        ]
      ],
      [
        "mahType",
        "MAH类型",
        [
          "化学药制剂 MAH 批件",
          "生物药制剂 MAH 批件",
          "中药 MAH 批件",
          "其他批件"
        ]
      ],
      [
        "approvalStatus",
        "批件状态",
        [
          "已获批",
          "其他状态"
        ]
      ],
      [
        "tradeMode",
        "交易模式",
        [
          "MAH 转让",
          "股权并购",
          "委托生产",
          "其他合作模式"
        ]
      ]
    ]
  ],
  [
    "data",
    "数据",
    [
      [
        "kind",
        "交易意向",
        [
          "supply",
          "demand"
        ]
      ],
      [
        "dataType",
        "数据类型",
        [
          "临床研究数据",
          "真实世界RWD数据",
          "其他数据"
        ]
      ],
      [
        "complianceMaturity",
        "合规成熟度",
        [
          "仅限研究使用",
          "已脱敏合规",
          "可商用授权",
          "其他"
        ]
      ],
      [
        "cooperationMode",
        "合作模式",
        [
          "数据永久授权",
          "单次项目调取",
          "其他模式"
        ]
      ]
    ]
  ],
  [
    "talent",
    "人才",
    [
      [
        "kind",
        "交易意向",
        [
          "supply",
          "demand"
        ]
      ],
      [
        "talentType",
        "人才类型",
        [
          "首席科学家",
          "研发型人才",
          "投融资产业专家",
          "商业化运营人才",
          "其他人才"
        ]
      ],
      [
        "talentMaturity",
        "人才成熟度",
        [
          "资深专家",
          "初级从业者"
        ]
      ],
      [
        "cooperationMode",
        "合作模式",
        [
          "全职",
          "项目制",
          "其他模式"
        ]
      ]
    ]
  ],
  [
    "service",
    "服务机构",
    [
      [
        "kind",
        "交易意向",
        [
          "supply",
          "demand"
        ]
      ],
      [
        "serviceType",
        "服务类型",
        [
          "CXO服务",
          "骊珠整体解决方案",
          "增值服务"
        ]
      ],
      [
        "qualification",
        "机构资质",
        [
          "丰富案例"
        ]
      ],
      [
        "cooperationMode",
        "合作模式",
        [
          "单项目合作",
          "年度框架合作",
          "其他模式"
        ]
      ]
    ]
  ]
];
assert.deepEqual(schema.enterprise.categories.map(c=>[c.value,c.label]),expected.map(c=>c.slice(0,2)));
for(const [category,,fields] of expected) {
 const filters=schema.enterprise.filtersByCategory[category];
 assert.deepEqual(filters.map(f=>[f.key,f.label,f.options.filter(o=>o.value!=='all').map(o=>o.value)]),fields,category);
 assert.equal(new Set(filters.map(f=>f.key)).size,4);
 assert.ok(!filters.some(f=>f.key==='sort'));
}
const {resourceFilters,resourcePayload}=require(path.join(root,'src/main/resources/static/admin/admin.js'));
for(const [type]of expected)assert.equal(resourceFilters(schema,'enterprise',type).length,4);
const original={resourceType:'patent',attributes:{patentField:'药物化学',cooperationMode:'独占许可',enterprisePatentField:'小分子',enterpriseCooperationMode:'专利授权'}};
const changed=resourcePayload(schema,original,'patent',{enterprisePatentField:'抗体'});
assert.equal(changed.patentField,'药物化学','enterprise edits preserve scientist field');
assert.equal(changed.cooperationMode,'独占许可');
assert.equal(changed.enterprisePatentField,'抗体');
console.log('PASS final enterprise diagram contract and other-role attribute preservation');
